import {
  fromJsonSchema,
  type StandardSchemaWithJSON,
} from "@modelcontextprotocol/server";
import { z } from "zod";
import { zodToJsonSchema } from "zod-to-json-schema";

/**
 * MCP-only adapter. Preserve the existing Zod 3 runtime contract (defaults,
 * refinements, stripping and transformations), rather than migrating the
 * operation validators along with the transport. JSON Schema is generated by
 * the same converter as SDK v1 and retains its explicit draft-07 dialect.
 * SDK v2's public fromJsonSchema primitive supplies the schema interface.
 */
export function mcpSchema<S extends z.ZodTypeAny>(
  schema: S,
  io?: "input" | "output",
): StandardSchemaWithJSON<z.input<S>, z.output<S>>;
export function mcpSchema<S extends z.ZodRawShape>(
  shape: S,
  io?: "input" | "output",
): StandardSchemaWithJSON<z.input<z.ZodObject<S>>, z.output<z.ZodObject<S>>>;
export function mcpSchema(
  schemaOrShape: z.ZodTypeAny | z.ZodRawShape,
  io: "input" | "output" = "input",
): StandardSchemaWithJSON<any, any> {
  const schema =
    schemaOrShape instanceof z.ZodType
      ? schemaOrShape
      : z.object(schemaOrShape);
  const jsonSchema = zodToJsonSchema(schema, {
    strictUnions: true,
    target: "jsonSchema7",
    pipeStrategy: io,
  });
  const wrapped = fromJsonSchema(
    jsonSchema as Parameters<typeof fromJsonSchema>[0],
    {
      getValidator: () => (data: unknown) => {
        const result = schema.safeParse(data);
        return result.success
          ? { valid: true as const, data: result.data }
          : {
              valid: false as const,
              data: undefined,
              errorMessage: "Invalid tool arguments.",
            };
      },
    },
  );
  // Async refinements, where present, must keep their established semantics.
  return {
    "~standard": {
      ...wrapped["~standard"],
      validate: async (data: unknown) => {
        const result = await schema.safeParseAsync(data);
        return result.success
          ? { value: result.data }
          : {
              issues: result.error.issues.map(({ path, message }) => ({
                path,
                message,
              })),
            };
      },
    },
  };
}
